### ISSUE TITLE
Matrix subtraction actually adds elements instead of subtracting

### ISSUE THREAD

**Issue by neilbalch** [m516/TinyMatrixMath#2]
I think this is a bug:

```
Matrix<n,m>
        operator -(const Matrix<n,m> &other) const
        {
            Matrix<n,m> M;
            for(Size i = 0; i < n; i++)
            for(Size j = 0; j < m; j++)
            M[i][j]=data[i][j]+other.data[i][j];
            return M;
        }
```

Unless I'm mistaken, the `+` should be a `-`. This is the source code cloned from PlatformIO using this library listing: https://registry.platformio.org/libraries/m516/TinyMatrixMath

**Comment by m516** [comment]
Yikes, good catch! This issue has just been fixed and should be available when PlatformIO updates its repository database tomorrow. I'll leave this issue open until then.

**Comment by m516** [comment]
Those changes are in the [registry](https://registry.platformio.org/libraries/m516/TinyMatrixMath) now, and the status badge should update soon.

Closing this issue now. Thanks again for the tip!
